name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js 21 with nvm
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: |
        npm install -g expo-cli

    - name: Install EAS CLI
      run: |
        npm install -g eas-cli

    - name: Log in to Expo
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      run: expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD --non-interactive

    - name: Build APK for Production
      if: github.ref == 'refs/heads/main'
      run: eas build --platform android --profile production --non-interactive
