name: Build APK

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Log in to Expo
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      run: expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD --non-interactive

    - name: Build APK for Staging
      if: github.ref == 'refs/heads/staging'
      run: eas build --platform android --profile staging --non-interactive

